[logger]
filter = "info"
color = true
log_to_file = true
log_to_stdout = true
file = "/var/log/miner/ckb-miner/ckb-miner.log"

[sentry]
# set to blank to disable sentry error collection
dsn = "https://48c6a88d92e246478e2d53b5917a887c@sentry.io/1422795"
# if you are willing to help us to improve,
# please leave a way to contact you when we have troubles to reproduce the errors.
# org_contact = ""

[miner]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true
# block template polling interval in milliseconds
poll_interval = 1000
# how many cpu miners you want to run
cpus = 0

# only work if a gpu miner was built in.
[[ miner.gpus ]]
# the platform you want to use runing miner, can be 0,1,2,...
plat_id = 0
# the gpu you want to use runing miner, can be 0,1,2,3,...
gpu_ids = [0]